name: Build FoxIDE

on: workflow_dispatch

# on:
#   push:
#     branches:
#       - main
#       - release/*
#   pull_request:
#     branches:
#       - main
#       - release/*

jobs:
  # windows
  windows:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: microsoft/vscode
          ref: 1.85.1

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      - name: Run Compile
        run: |
          npm install -g node-gyp yarn
          yarn
          yarn gulp vscode-win32-x64
          cd ..
          dir

  # macOS x64
  darwin-x64:
    name: macos-x64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: microsoft/vscode
          ref: 1.85.1

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      - name: Run Compile
        run: |
          npm install -g node-gyp yarn
          yarn
          yarn gulp vscode-darwin-x64
          cd ..
          dir

  # macOS arm
  darwin-arm:
    name: macos-arm
    runs-on: macos-arm64
    steps:
      - uses: actions/checkout@v4
        with:
          repository: microsoft/vscode
          ref: 1.85.1

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      - name: Run Compile
        run: |
          npm install -g node-gyp yarn
          yarn
          yarn gulp vscode-darwin-arm64
          cd ..
          dir
