name: CI

on: workflow_dispatch

# on:
#   push:
#     branches:
#       - main
#       - release/*
#   pull_request:
#     branches:
#       - main
#       - release/*

jobs:
  windows:
    name: Windows
    runs-on: windows-2022
    timeout-minutes: 60
    env:
      CHILD_CONCURRENCY: "1"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "microsoft/vscode"
          ref: "1.85.1"

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"

      - name: Compile and Download
        run: |
          yarn
          yarn npm-run-all --max_old_space_size=4095 -lp compile "electron x64" playwright-install download-builtin-extensions

  darwin:
    name: macOS
    runs-on: macos-latest
    timeout-minutes: 40
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "microsoft/vscode"
          ref: "1.85.1"

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Compile and Download
        run: |
          yarn
          yarn npm-run-all --max_old_space_size=4095 -lp compile "electron x64" playwright-install download-builtin-extensions
