name: CI

on: workflow_dispatch

# on:
#   push:
#     branches:
#       - main
#       - release/*
#   pull_request:
#     branches:
#       - main
#       - release/*

jobs:
  build:
    name: ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [windows, darwin-x64, darwin-arm64]
        include:
          - build: windows
            os: windows-latest
            commond: vscode-win32-x64
            dist: VSCode-win32-x64

          - build: darwin-x64
            os: macos-latest
            commond: vscode-darwin-x64
            dist: VSCode-darwin-x64

          - build: darwin-arm64
            os: macos-latest
            commond: vscode-darwin-arm64
            dist: VSCode-darwin-arm64
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/vscode
          ref: 1.85.1
          path: vscode

      - uses: actions/checkout@v3
        with:
          ref: master
          path: foxide

      - if: ${{ matrix.build == 'windows' }}
        name: Replace Files
        run: xcopy foxide\* vscode /y /e /i /q
      - if: ${{ matrix.build == 'darwin-x64' }} || ${{ matrix.build == 'darwin-arm64' }}
        name: Replace Files
        run: mv -f foxide/* vscode
      - run: cd vscode

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.x

      - name: Build FoxIDE
        run: |
          npm install -g node-gyp yarn
          yarn
          yarn gulp ${{ matrix.commond }}
      - run: cd ..
      
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build }}
          path: ${{ matrix.dist }}
