name: CI

on: workflow_dispatch

# on:
#   push:
#     branches:
#       - main
#       - release/*
#   pull_request:
#     branches:
#       - main
#       - release/*

jobs:
  windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          repository: microsoft/vscode
          ref: 1.85.1

      - uses: actions/setup-node@v4
        with:
          node-version: 18.15.x

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12.1
      
      - run: yarn
      - run: yarn gulp vscode-win32-x64

  darwin:
    name: macOS
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
        with:
          repository: microsoft/vscode
          ref: 1.85.1

      - uses: actions/setup-node@v4
        with:
          node-version: 18.15.x

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12.1

      - run: yarn
      - run: yarn gulp vscode-darwin-x64
