name: CI

on: workflow_dispatch

# on:
#   push:
#     branches:
#       - main
#       - release/*
#   pull_request:
#     branches:
#       - main
#       - release/*

jobs:
  build:
    name: ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [windows, darwin-x64, darwin-arm]
        include:
          - build: windows
            os: windows-latest
            commond: vscode-win32-x64
            dist: VSCode-win32-x64

          - build: darwin-x64
            os: macos-latest
            commond: vscode-darwin-x64
            dist: VSCode-darwin-x64

          - build: darwin-arm
            os: macos-latest
            commond: vscode-darwin-arm
            dist: VSCode-darwin-arm
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/vscode
          ref: 1.85.1

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.x

      - name: Run Build
        run: |
          npm install -g node-gyp yarn
          yarn
          yarn gulp ${{ matrix.commond }}

      - uses: actions/cache@v3
        id: cache
        with:
          path: ../${{ matrix.dist }}
          key: foxide-${{ matrix.build }}
